manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect

  projects:
     # The Nordic Connect SDK Manifest
    # This automatically includes Zephyr, mbedtls, mcuboot, and the proprietary libraries.
      - name: sdk-nrf
        remote: nrfconnect
        revision: v3.2.1
        path: nrf
        import: true
        west-commands: scripts/west-commands.yml
      
  self:
    path: BabbiesTracker
